apiVersion: apps/v1
kind: Deployment
metadata:
  name: project4-deploy
  labels:
    app: project4
spec:
  selector:
    matchLabels:
      app: project4
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: project4
    spec:
      containers:
      - name: project4
        image: leoadams/project4:latest
        #imagePullPolicy: Always
        ports:
          - containerPort: 80
